### PR TITLE
Skatehive Ipfs Iframe REGEX add

### PR DESCRIPTION
**Pull request by sktbrd**
I hope its right ! Thanks for the patience with us

### CODE REVIEW

**Comment by feruzm** [comment]
@sktbrd this should work, only your linter added `;` in every line, could you remove or don't add them to keep consistent coding style? Thanks.

**Comment by sktbrd** [comment]
@feruzm I removed the `;`

**Comment by sktbrd** [comment]
image


weird , may be it takes some time ?

**Comment by feruzm** [comment]
@sktbrd it is not pushed to production yet, check https://alpha.ecency.com

**Pull request merged**
